### ISSUE TITLE
zsh azure plugin

### ISSUE THREAD

**Issue by za** [dmakeienko/azcli#2]
:memo: Note: zsh azure plugin is available here: https://github.com/ohmyzsh/ohmyzsh/blob/80c114cb3a64044ea50b623f96a35bc022db5e8d/plugins/azure/README.md?plain=1#L6

> To use it, add `azure` to the plugins array in your zshrc file.

```zsh
plugins=(... azure)
```

**Comment by dmakeienko** [comment]
Thanks!
